name = "Create Adventured"
author = "evictedcucumber"
version = "1.0.0"
recommended-ram = "8192"
pack-format = "packwiz:1.1.0"
platform = "curseforge"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5adae5f885cfe6b5758f8380bc20e522036f0aaadcba4507ea7fe63bf9f27eae"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.227"
