name = "Create Adventured"
author = "evictedcucumber"
version = "1.0.0"
recommended-ram = "8192"
pack-format = "packwiz:1.1.0"
platform = "curseforge"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a47fa4a3bd7488601b46cbaa48d5f7968f5e3dabfb1419c589641c24f0a05079"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.227"
