name = "Create Adventured"
author = "evictedcucumber"
version = "1.0.0"
recommended-ram = "8192"
pack-format = "packwiz:1.1.0"
platform = "curseforge"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9f80359684c7b2ca819481f5aee4c55da3af591b4ab826b6bc3ded2b76b02ff7"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.227"
